name: TFMCBA
version: "1.0"
main: me.therealdan.tfmcba.TFMCBA
api-version: "1.16"
author: TheRealDan

depend: [TheForceMC, BattleArena]

commands:
  TFMCBA:
    description: TFMCCommand
    permission: tfmcba.commands.tfmcba